### ISSUE TITLE
DILA 佛學術語字辭典API回應500

### ISSUE THREAD

**Issue by MrMYHuang** [DILA-edu/cbeta-api#11]
各位大德您好：
今天發生使用DILA 佛學術語字辭典API，卻回傳：
{"status":500,"error":"Internal Server Error"}

例如這個API call：
http://glossaries.dila.edu.tw/search.json?type=all&term=菩薩

麻煩處理。謝謝。

**Comment by RayCHOU** [comment]
我沒做什麼處理，剛試是好的，
麻煩您再試試看？

**Comment by MrRogerHuang** [comment]
> 我沒做什麼處理，剛試是好的，
> 麻煩您再試試看？

謝謝，現在好了。

status 500一般是後端程式有未處理的exception而中止。我猜測可能是後端程式呼叫第3方字典的API call出現異常，因為後端沒變動下，功能異常又回復正常，應該是第3方API call的結果有變動...
