### ISSUE TITLE
HTML文檔缺<br> tag

### ISSUE THREAD

**Issue by MrRogerHuang** [DILA-edu/cbeta-api#12]
各位大德您好：

如圖所示為[《太虛大師年譜》：「太虛大師年譜」(CBETA 2020.Q4, Y13, no. 13, p. 1a1)](https://cbetaonline.dila.edu.tw/zh/Y0013_002)一處瀏覽器擷圖：
![image](https://user-images.githubusercontent.com/49478723/101139512-9d55ea80-364c-11eb-8a87-13f72b567102.png)
左方的文字有用`<br>`正確作換行。

但我的app使用CBETA API取得的HTML卻缺少該換行`<br>` tag：
![image](https://user-images.githubusercontent.com/49478723/101138704-8367d800-364b-11eb-8946-6c3a0d6b1c79.png)

[太虛大師年譜卷2 CBETA API call](https://cbdata.dila.edu.tw/v1.2/juans?edition=CBETA&work_info=1&work=Y0013&juan=2)

請問如何處理？

**Comment by RayCHOU** [comment]
因為前端在呈現時有「依原書換行」與「不依原書換行」兩種選擇，
所以當時與前端開發者 @winxd 討論的結果是：

    API 提供 <span class="lb"> 標記，
    前端視需要判斷是否轉為 <br>.

**Comment by MrRogerHuang** [comment]
了解，謝謝您。

**Comment by MrMYHuang** [comment]
補充：我研究出來是pre class HTML element裡的lb class HTML elements都需要它們前面加上斷行。JS的參考作法：
```
function addCbetaLineBreaks() {
  document.querySelectorAll('.pre .lb').forEach((el) => {
    const newBr = document.createElement('br');
    el.before(newBr);
  });
}
```
完成範例：
![image](https://user-images.githubusercontent.com/12458706/101183254-3ce59e00-368a-11eb-840d-18db29b3e786.png)
