### ISSUE TITLE
《諸經日誦集要卷下》HTML有不合法的屬性

### ISSUE THREAD

**Issue by MrMYHuang** [DILA-edu/cbeta-api#16]
各位大德您好：

我發現CBETA API回傳《諸經日誦集要卷下》的HTML出現不合法的element attribute，也就是這個API call:
https://cbdata.dila.edu.tw/v1.2/juans?edition=CBETA&work_info=1&work=JB044&juan=3

當中搜尋"晝夜六時恒吉祥"會看到這一段：
```
<div class='lg-cell' 1><span class=\"t\" l=\"0176b08\" w=\"8\">晝夜六時恒吉祥<span class=\"pc\">；</span></span></div>
```
第1個div有一個數字1的不合法屬性。由於HTML parser對語法的容錯很強，一般瀏覽器會忽略它。

但我開發的CBETA reader app使用ePub的技術打包CBETA API回傳的HTML為XHTML，而ePub會用XML parser作語法檢查，因此此不合法屬性就會造成頁面顯示錯誤。

請問貴單位能不能移除此不合法的HTML屬性？

**Comment by RayCHOU** [comment]
檢查確認有這問題，
將進行修正。

**Comment by RayCHOU** [comment]
開發版已修正了： https://cbdata.dila.edu.tw/dev/juans?work=JB044&juan=3
不過因為目前正在進行 2021.Q1 的資料更新，
為維持正式版的版本穩定，
這個 issue 的修訂將與 2021.Q1 一起更新。
2021Q1 正式版預定連同 CBETA Online 新版一起於年後對外發佈，
時間應會在 2/26 之前。

**Comment by RayCHOU** [comment]
這個問題已經解決了。
