### ISSUE TITLE
藏經底本不清楚的字 <unclear>

### ISSUE THREAD

**Issue by RayCHOU** [DILA-edu/cbeta-api#3]
藏經底本不清楚的字，如果猜得出來是什麼字，在 CBETA XML [I01n0001_p0003b13](https://github.com/cbeta-git/xml-p5a/blob/8814faac80c4b4d435e90ed65099205d6b043192/I/I01/I01n0001.xml#L94) 有如下紀錄：

```xml
<unclear cert="low" reason="damage">遞</unclear>
```

CBETA API 提供的 HTML 如下：

```HTML
<span class="unclear" data-cert="low"><span class="t" l="0003b13" w="6">遞</span></span>
```

在 [CBETA Online](https://cbetaonline.dila.edu.tw/zh/I01n0001_p0003b13) 呈現 mouse over 時會有訊息「本字為推測字，信心程度：低」

如果根本猜不出來是什麼字，就單純標 `<unclear>`，例如： [K35n1257_p0334c01](https://raw.githubusercontent.com/cbeta-git/xml-p5a/master/K/K35/K35n1257.xml)

```XML
作𡦢<unclear/>二字
```

CBETA API 提供的 HTML  如下：
```HTML
<span class="t" l="0334c01" w="1">作𡦢</span>
<span class="unclear" data-cert="">▆</span>
<span class="t" l="0334c01" w="3">二字
```

目前在 [CBETA Online 呈現](https://cbetaonline.dila.edu.tw/zh/K35n1257_p0334c01) mouse over 時呈現「本字為推測字，信心程度：」

CBETA CBReader 開發者 heaven 的建議是「純粹是 `<unclear/>` 就不提示了」。
但是因為這裡的情況是「底本文字無法辨識」，而我們以「▆」來表示，底本並不是真的有「▆」這個黑方塊。
所以我覺得有提示還是比較好，但是不要說「本字為推測字」，或許是說「底本文字無法辨識」。

CBETA API 提供的 HTML 就還是如下：
```HTML
<span class="unclear">▆</span>
```

由前端來判斷如何呈現。
這樣大家覺得如何？

**Comment by jenjouhung** [comment]
建議註解改作：「此處文字無法辨識」

**Comment by RayCHOU** [comment]
今天與 CBETA Online 開發者討論的結果是：
CBETA API 的輸出不變，
由前端判斷顯示「此處文字無法辨識」

**Comment by heavenchou** [comment]
我後來發現，目前新版的 CBReader 是有提示為「未知的文字」，早期是沒有提示的，大概我後來改了卻忘了。 :)
