### ISSUE TITLE
DNS 異常

### ISSUE THREAD

**Issue by MrMYHuang** [DILA-edu/cbeta-api#38]
約 2022/11/30 11:30 pm 發生：
![image](https://user-images.githubusercontent.com/12458706/204846162-4a8cec92-1b14-4b76-9108-e719968146a3.png)

使用瀏覽器或 nslookup 皆異常。

**Comment by RayCHOU** [comment]
現在好像好了？

**Comment by MrMYHuang** [comment]
> 現在好像好了？

問題還在，中華電信的 DNS 可查得到，Google 的 (8.8.8.8) 不行。
![image](https://user-images.githubusercontent.com/12458706/204939582-b4a0eca7-bd25-4a1c-b620-4fbfcf3b979f.png)

**Comment by RayCHOU** [comment]
解決了，感謝回報.

```
nslookup cbetaonline.dila.edu.tw 8.8.8.8
Server:		8.8.8.8
Address:	8.8.8.8#53

Non-authoritative answer:
Name:	cbetaonline.dila.edu.tw
Address: 140.131.255.126
```

**Comment by MrMYHuang** [comment]
謝謝您。阿彌陀佛。

**Comment by MrMYHuang** [comment]
您好，

又發生 DNS 查詢異常，但中華電信 DNS 查詢正常的問題：
![image](https://github.com/DILA-edu/cbeta-api/assets/12458706/afe8bcd0-e68f-40be-aa8e-58708eddfab7)

**Comment by RayCHOU** [comment]
網管人員回復處理了，
請再看看，
感謝回報。

**Comment by MrMYHuang** [comment]
測試正常，謝謝您。

阿彌陀佛
