### ISSUE TITLE
CBETA Online 無法連線

### ISSUE THREAD

**Issue by MrMYHuang** [DILA-edu/cbeta-api#43]
您好：

目前無法開啟 https://cbetaonline.dila.edu.tw/

瀏覽器回應 ERR_CONNECTION_TIMED_OUT.

**Comment by RayCHOU** [comment]
您好，

已將您回報的問題轉給 CBETA Online 網站管理者，
Contact：winxd@dila.edu.tw
@winxd 

Online 管理者並不會查看這裡 API 的 issue,
Online 的問題建議您直接向 Online 提出，
雖然我也可以為您轉達，
但總是隔了一層。

**Comment by MrMYHuang** [comment]
> 您好，
> 
> 已將您回報的問題轉給 CBETA Online 網站管理者， Contact：[winxd@dila.edu.tw](mailto:winxd@dila.edu.tw) (可在 Online 首頁看到) @winxd
> 
> Online 管理者並不會查看這裡 API 的 issue, Online 的問題建議您直接向 Online 提出， 雖然我也可以為您轉達， 但總是隔了一層。

好的，之後會透過該 E-mail 回報。謝謝您。阿彌陀佛。
