### ISSUE TITLE
能否在api中返回查詢經文所在的頁碼？

### ISSUE THREAD

**Issue by sunyrain** [DILA-edu/cbeta-api#44]
能否在api中返回查詢經文所在的頁碼？類似於《新集藏經音義隨函錄(第13卷-第30卷)》卷17：「[幻-ㄠ+糸]術」(CBETA, K35, no. 1257, p. 189b6), 組字式 escape 之後：[幻-ㄠ%2B糸] 里的 CBETA, K35, no. 1257, p. 189b6

**Comment by RayCHOU** [comment]
有兩種方法：

一、
先呼叫 https://cbdata.dila.edu.tw/stable/sphinx?q=[幻-ㄠ%2B糸]
得知它出現在：

    "work": "K1257",
    "juan": 17

然後再呼叫 https://cbdata.dila.edu.tw/stable/kwic3/juan?work=K1257&juan=17&q=[幻-ㄠ+糸]
得到 `"lb": "0189b06"`

二、使用 all_in_one
呼叫 https://cbdata.dila.edu.tw/stable/sphinx/all_in_one?q=[幻-ㄠ+糸]
得到
```json
"kwics": {
  "num_found": 1,
  "results": [
    {
      "offset_in_text_with_punc": 25219,
      "lb": "0189b06",
      "kwic": "。雜藥(上在合反)。<mark>󰂒</mark>術(上戶辦反詐惑也正"
    }
  ]
}
```

**Comment by sunyrain** [comment]
萬分感謝
