### ISSUE TITLE
CBETA HTML經文檔inline style的問題與建議

### ISSUE THREAD

**Issue by MrRogerHuang** [DILA-edu/cbeta-api#7]
各位大德：

最近我的非官方CBETA閱讀器app在處理《太虛大師年譜》卷2的格式問題：
https://cbetaonline.dila.edu.tw/zh/Y0013_002
我發現此HTML檔有使用inline style:
![image](https://user-images.githubusercontent.com/49478723/96819317-de57be00-1455-11eb-972d-b53cc84a7659.png)
也就是在HTML tag不使用class，而是style屬性指定樣式，例如：
```
<p style="margin-left: 2em; text-indent: -1em; display: block;">
...
```
這樣式在經文作"橫式左至右書寫"排版沒問題。但在經文作"直式上至下書寫"就會發生段落行首沒正確保留"top margin"下，又作text-indent: -1em，導致文字超出上邊界，如圖所示：
![image](https://user-images.githubusercontent.com/49478723/96820237-1fe96880-1458-11eb-93f9-13e55e49e40b.png)
我的app目前解決作法是：在直式模式下，搜尋HTML所有"left-margin"字串，取代為"top-margin"。

但我認為較安全的作法應該是此種style應該以CSS class方式定義，例如：
```
<p class="indent">
...
```
而indent class可由外部樣式表作不同定義。例如：
```
/* CSS file 1 */
.indent {
  margin-left: 2em;
  text-indent: -1em;
  display: block;
}
```
```
/* CSS file 2 */
.indent {
  margin-top: 2em;
  text-indent: -1em;
  display: block;
}
```
使用CSS class作法也是CBETA HTML目前許多樣式的指定作法(如lb, noteAnchor, doube-line-note CSS classes)。
如果不方便對現有HTML文件作更動，仍建議未來多用CSS class設定樣式，而不是inline style！？

**Comment by RayCHOU** [comment]
我支持「CBETA API 在 HTML 儘量用 class 取代 style」這樣的想法。
看 CBETA Online 前端開發者 @winxd 是否同意。

[Y13n0013_p0019a03](https://cbetaonline.dila.edu.tw/zh/Y13n0013_p0019a03) 這地方的 CBETA XML 是這樣：

```xml
<p xml:id="pY13p0019a0304" style="margin-left:2em;text-indent:-1em">
```

如果 XML 改成這樣：

```xml
<p xml:id="pY13p0019a0304" rend="m2 o1">
<!-- m2 表示內縮 (margin) 2格, o1 表示凸排 (outdent) 1格 -->
```

那麼 XML 轉成 HTML 使用 class 就很容易。
不過修改 XML 要請問 CBETA 總幹事 @mahawu 以及 CBReader 開發者 @heavenchou  的意見。
(類似做法，我們以前曾討論過)

如果 XML 不改，而是 CBETA API 提供的 HTML 做改變，
這我這邊可以嘗試看看，但是不知道會不會有什麼副作用。

**Comment by winxd** [comment]
前端沒有一定要使用 inline style，有需要前端也可以自行做其他的轉換，所以改成 classes 基本上 ok 。

惟需將 classes 可能的規則列出來，以方便寫入外部的樣式檔。

**Comment by heavenchou** [comment]
以前是為了避免太多種寫法會造成混淆, 例如有人同時寫 rend 和 style , 就麻煩了.

不過若現有的情況會造成困擾, 那麼改成 rend 也是可以考慮的.

不知在使用直排時, 是只有圖檔的 margin-left 需要改成 margin-top? 或是像 p , div 也都需要如此改?

因為牽涉到的東西不少, 格式的問題要先私下討論討論了.

**Comment by MrRogerHuang** [comment]
> 以前是為了避免太多種寫法會造成混淆, 例如有人同時寫 rend 和 style , 就麻煩了.
> 
> 不過若現有的情況會造成困擾, 那麼改成 rend 也是可以考慮的.
> 
> 不知在使用直排時, 是只有圖檔的 margin-left 需要改成 margin-top? 或是像 p , div 也都需要如此改?
> 
> 因為牽涉到的東西不少, 格式的問題要先私下討論討論了.

大德您好：

我目前遇到的問題是文字段落<p>的縮/凸排問題，可能未來有<div>的文字段落。
但若此縮/凸排樣式太多種，要一一改寫成CSS classes的確會是個困難。

完美的解法應該是改用text-indent的hanging，直排就不必把margin-left改成margin-top：
https://developer.mozilla.org/en-US/docs/Web/CSS/text-indent
可惜目前沒有瀏覧器支援...

**Comment by RayCHOU** [comment]
> 以前是為了避免太多種寫法會造成混淆, 例如有人同時寫 rend 和 style , 就麻煩了.

XML 的 rend 和 style，相當於 HTML 的 class 和 style，它們是允許同時存在的。
當它們同時存在時，XML 的 style 優先於 rend，HTML 的 style 優先於 class。

@heavenchou 說的可能是 XML rend 指定了 m1，style 卻又給了另一個 margin-left，
這就是 XML 標記人員的問題了，不是標記機制的問題。
這也不會造成機制的混亂，就是結果可能不如標記人員的預期，應該要修改標記。

不過 @heavenchou 說的讓我聯想到，
假設 XML `<p type="dharani">` 預設 HTML 為 `<p class="dharani">`，
那麼 XML `<p type="dharani" rend="m1">` 的 HTML 是 `<p class="dharani m1">`，
如果 dharani, m1 這兩個 class 都定義了 margin-left，會使用哪一個？
有固定的優先序準則可以依循嗎？
或是這種情況可以依靠標記規則來避免。

**Comment by MrRogerHuang** [comment]
> 那麼 XML `<p type="dharani" rend="m1">` 的 HTML 是 `<p class="dharani m1">`，
> 如果 dharani, m1 這兩個 class 都定義了 margin-left，會使用哪一個？
> 有固定的優先序準則可以依循嗎？
> 或是這種情況可以依靠標記規則來避免。

大德您好：

針對這個CSS rule優先問題，有一說是"[last parsed, last applied](https://stackoverflow.com/a/2876609/631869)"，範例：
https://jsfiddle.net/zkc8sa6o/

無關class c1, c2在div的class list的出現順序，class c2是較後parsed，所以它的CSS rules優先序是較高的。

**Comment by heavenchou** [comment]
我剛試了一下, 在直排時 text-indent 作用正常, 但 margin-left 真的是作用在左邊, 應該要改成 margin-top 才對.

> 這就是 XML 標記人員的問題了，不是標記機制的問題。

對啊, 都是人的問題, 彈性太大了, 人總會弄錯的. 有時錯了還看不出來, 那才麻煩. 😄 

依這個情況來看, 那反而要要求標記人員不能直接寫 sytle , 一定要用 rend 才行. 所以原本的 sytle 和 rend 都要規劃一下.

CBReader 是有原書格式, 所以在程式中還需要自己去分析 style 的內容, 才能算出每一行行首的空格, 現在要改成分析 rend , 這都是麻煩事, 所以處理起來沒有那麼快喔. ^^

>`假設 XML <p type="dharani"> 預設 HTML 為 <p class="dharani">，`
>`那麼 XML <p type="dharani" rend="m1"> 的 HTML 是 <p class="dharani m1">，`

嗯, 這個也要先規劃好, 不要讓它們重複了. 例如 dharani 只處理顏色或大小, 不處理排版格式.

> 無關class c1, c2在div的class list的出現順序，class c2是較後parsed，所以它的CSS rules優先序是較高的。

是的, 所以 CBReader 在 css 的最後就是載入使用者自訂的, 使用者可以決定最後的呈現.

若使用者要在 class="dharani" 處理排版, 或是要在 class="m1" 處理顏色, 那就是使用者自行負責了. 🤣

**Comment by RayCHOU** [comment]
> 無關class c1, c2在div的class list的出現順序，class c2是較後parsed，所以它的CSS rules優先序是較高的。

感謝說明，我請教了同事，同事幫忙測試，跟您說的一樣。
所以前端可以控制 CSS rule 的先後順序。

**Comment by RayCHOU** [comment]
> CBReader 是有原書格式, 所以在程式中還需要自己去分析 style 的內容, 才能算出每一行行首的空格, 現在要改成分析 rend , 這都是麻煩事, 所以處理起來沒有那麼快喔. ^^

XML 要改的話，的確快不了，也要更謹慎。
所以我在想，或許下一季可以由 API 這邊先改，
我也把各種 class 對照表列出來，例如 m1 對應到 margin-left:1em,
前端可以先測試一下。

因為 XML 要改的話，也不可能是手動去一個一個改，
一定是程式整批取代，
上述的測試也等於是先測一下會不會有什麼沒想到的問題。
如果有問題，要再改回來，也比較容易。

而以後 XML 如果改了的話，
前端也不必變動，API 這邊改就好了。

**Comment by RayCHOU** [comment]
> 完美的解法應該是改用text-indent的hanging，直排就不必把margin-left改成margin-top：
> https://developer.mozilla.org/en-US/docs/Web/CSS/text-indent
> 可惜目前沒有瀏覧器支援...

長知識了，我還不知道有 hanging 這東西，
凸排的確應該用它才對。
可惜 browser 不支援的話，都是白搭⋯⋯

或許未來可以這麼設計，
class h2 表示 hanging 2格，相當於：`margin-left:2em;text-indent:-2em;`

XML 就更簡潔了： `<p rend="h2">`

**Comment by heavenchou** [comment]
> 所以我在想，或許下一季可以由 API 這邊先改，
> 我也把各種 class 對照表列出來，例如 m1 對應到 margin-left:1em,
> 前端可以先測試一下。

可以啊, 到時細節我們就再討論了.

**Comment by RayCHOU** [comment]
今天寫個小程式整理一下大概有這些：

h 表示 hanging, h1 表示除了首行之外都縮一格
h0 => margin-left:0em;text-indent:-0em
h1 => margin-left:1em;text-indent:-1em
依此類推一直到 h15

m0 => margin-left:0em;
m1 => margin-left:1em
依此類推一直到 m40
m40 實在是太大了！我再跟 CBETA 確認是否有誤。

o 表示 outdent，o1 表示凸排1格
o1 => text-indent:-1em
o2 => text-indent:-2em
依此類推到 o14

i 表示 indent, i1 表示首行縮排1格
i0 => text-indent:0em;
i1 => text-indent:1em;
依此類推一直到 i13
(有個 i22 待確認)

上述的 class 命名設計看大家覺得如何。
因為現在正在做 Q4,
請 @winxd 看看是 Q4 就要開始實做？或是下季再做？

**Comment by winxd** [comment]
目前手上有更多其它待趕工的工作，這季做是不太可能了

至於是否要下季做，我想就內部會議再討論了，工作上的安排得經由主管同意

**Comment by RayCHOU** [comment]
CBETA @mahawu 已確認：
* t22 是錯誤，已訂正。
* m29 ~ m40 已修正。
* m10 以上都要檢查一遍，不過數量太多，只能列入待辦。

**Comment by RayCHOU** [comment]
@MrRogerHuang 
CBETA Online 開發者 @winxd 「建議暫時先別動」，
所以 2021 Q1 仍不會做此修改。

**Comment by MrRogerHuang** [comment]
> @MrRogerHuang
> CBETA Online 開發者 @winxd 「建議暫時先別動」，
> 所以 2021 Q1 仍不會做此修改。

好，謝謝您。

**Comment by RayCHOU** [comment]
@MrRogerHuang 
這件事短期內大概都不會動了，
我先 Close.
