### ISSUE TITLE
KWIC3 搜索不到任何結果 #bug

### ISSUE THREAD

**Issue by briansun** [DILA-edu/cbeta-api#9]
例如：
https://cbdata.dila.edu.tw/v1.2/kwic3?q=法鼓

可能是出了 bug

**Comment by RayCHOU** [comment]
剛把 server reboot 就好了，不知道為什麼⋯⋯

**Comment by briansun** [comment]
謝謝！已經OK了。

如果是經常遇到這種情況，能否每日 reboot server 呢？

**Comment by RayCHOU** [comment]
目前似乎很少遇到，不知道是否有每日 reboot 的需要？
再觀察看看？

**Comment by briansun** [comment]
好。

**Comment by briansun** [comment]
問題再次出現。

**Comment by RayCHOU** [comment]
我猜可能是因為最近我在那部 server 上跑大量的 CRF learning,
這樣我把 CRF learning 停掉了，另外找機器做，
另外也把 web server 重啟了，
我們再觀察一下。
感謝。

**Comment by briansun** [comment]
嗯嗯。老師辛苦了！

**Comment by RayCHOU** [comment]
> 嗯嗯。老師辛苦了！

我不是老師，只是個小組員 ^_^
您叫我 Ray 或 邦信 都行！

**Comment by briansun** [comment]
好的好的。Ray，最近又有問題了。能搜到的內容非常少，例如 https://cbdata.dila.edu.tw/v1.2/kwic3?q=一切有為法

**Comment by RayCHOU** [comment]
感謝通知，
設定每天重啟 web server 了，
再觀察看看。

**Comment by briansun** [comment]
嗯。我覺得還是要找原因。爭取服務能穩定下來。我這邊用戶用搜索的也多。

（本條issue暫時不關閉）

**Comment by RayCHOU** [comment]
KWIC3 是我自己寫的 search engine, 還是比不上別人寫的好。
全文檢索建議先用 Sphinx: http://cbdata.dila.edu.tw/v1.2/static_pages/sphinx
有 sphinx 達不到的功能再用 kwic3.

**Comment by briansun** [comment]
原來是這樣，明白了。Sphinx 是否沒有返回上下文？

**Comment by RayCHOU** [comment]
> 原來是這樣，明白了。Sphinx 是否沒有返回上下文？

是的，CBETA API 的 Sphinx 沒回傳關鍵字的前後文。
有一個 all in one 會回傳前後文： http://cbdata.dila.edu.tw/v1.2/static_pages/sphinx_all_in_one
不過它其實還是先呼叫 sphinx, 再呼叫 kwic3, 然後再包裝起來而已。

Sphinx Search 其實有提供「關鍵字前後文」的功能 excerpts (snippets)：
http://sphinxsearch.com/docs/manual-2.3.2.html#api-func-buildexcerpts

但是我們之前測試不太符合需求，
Sphinx 新版不知道如何，有機會或許可以再試試。

我們也有考慮 Elasticsearch, 但是找不到「關鍵字總次數」的功能，
似乎是要自己寫 plugin.

**Comment by RayCHOU** [comment]
這個 bug 已經排除了。
